id: 0
addr:
  claw:
    ip: "0.0.0.0"
    port: 5301
  finger_0:
    ip: "0.0.0.0"
    port: 5302
  finger_1:
    ip: "0.0.0.0"
    port: 5303
  publisher:
    ip: "0.0.0.0"
    port: 6300

motor:
  bus_interface: socketcan
  bus_channel: can0
  motor_id: 1
  Kp_s: 2.0e-5
  Kp_b: 1.0e-4
  Kd: 1.0e-4
  iq_max: 10
  angle_max: 360.0

lead: 15.0
gear_radius: 15.0

camera_0:
  name: Left Camera
  params_path: "./config/camera/maixcam-a3a3.yaml"
camera_1:
  name: Right Camera
  params_path: "./config/camera/maixcam-9674.yaml"

finger_net_0:
  name: Finger Net 0
  model_path: "./models/FingerNet.onnx"

finger_net_1:
  name: Finger Net 1
  model_path: "./models/FingerNet.onnx"

phone:
  params_path: "./config/phone/phone_0.yaml"