mode: web
ip: "192.168.4.54"
port: 5555
width: 320
height: 240
dist:
  - - -0.154465
    - 0.047942
    - 0.000000
    - 0.000000
    - -0.025358
mtx:
  - - 182.075320
    - 0.000000
    - 160.242968
  - - 0.000000
    - 181.868915
    - 132.279192
  - - 0.000000
    - 0.000000
    - 1.000000
marker_size: 0.008
filter_on: True
filter_frame: 5
marker2global:
  translation:
    - - 0.0
      - 0.0
      - -25.0
  rotation:
    - - - 1.0
        - 0.0
        - 0.0
      - - 0.0
        - -1.0
        - 0.0
      - - 0.0
        - 0.0
        - -1.0