mode: web
ip: "192.168.4.137"
port: 5555
width: 320
height: 240
dist:
  - - -0.146602
    - 0.015541
    - 0.000000
    - 0.000000
    - -0.004605
mtx:
  - - 181.203037
    - 0.000000
    - 165.322286
  - - 0.000000
    - 181.070824
    - 106.557711
  - - 0.000000
    - 0.000000
    - 1.000000
marker_size: 0.008
filter_on: True
filter_frame: 5
marker2global:
  translation:
    - - 0.0
      - 0.0
      - -25.0
  rotation:
    - - - 1.0
        - 0.0
        - 0.0
      - - 0.0
        - -1.0
        - 0.0
      - - 0.0
        - 0.0
        - -1.0