mode: web
ip: "192.168.4.202"
port: 5555
width: 320
height: 240
dist:
  - - -0.148965
    - 0.033128
    - 0.000000
    - 0.000000
    - -0.015179
mtx:
  - - 182.304481
    - 0.000000
    - 153.305504
  - - 0.000000
    - 182.089675
    - 116.069124
  - - 0.000000
    - 0.000000
    - 1.000000
marker_size: 0.008
filter_on: True
filter_frame: 5
marker2global:
  translation:
    - - 0.0
      - 0.0
      - -25.0
  rotation:
    - - - 1.0
        - 0.0
        - 0.0
      - - 0.0
        - -1.0
        - 0.0
      - - 0.0
        - 0.0
        - -1.0